logs_directory: /tmp/mimosa/
world_frame: mimosa_world
body_frame: mimosa_body

imu:
  sensor_frame: mimosa_imu
  T_B_S: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0] # x, y, z, x, y, z, w
  manager:
    log_level: info
    max_buffer_duration: 1.1
    pose_init_wait_secs: 0.2
    interpolation_max_ts_diff: 1 #s
    extrapolation_max_ts_diff: 0.15 #s
    acc_scale_factor: 1 # Scales the acclerometer measurement. Default is 1, which means no scaling. Livox typically reports acc in g, so we need to scale it to m/s^2
  preintegration:
    acc_noise_density: 0.1 # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" ) # Datasheet ICM-20948 0.0022563
    acc_bias_random_walk: 0.01 # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
    gyro_noise_density: 0.026179938 # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" ) # Datasheet ICM-20948: 0.00026179938
    gyro_bias_random_walk: 0.001 # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
    integration_sigma: 0 # Unclear what this is. Set to 0 for now.
    use_2nd_order_coriolis: false
    use_estimated_gravity: false
    gravity_magnitude: 9.8122
    gravity_aligned_initialization: false

graph:
  manager:
    log_level: trace
    max_ts_diff_for_imu_breaking: 0.005
    max_measurement_latency: 0.1
    smoother:
      lag: 0.5
      wildfire_threshold: 0.001
      relinearize_threshold_translation: 5.0e-2
      relinearize_threshold_rotation: 1.75e-1
      relinearize_threshold_velocity: 5.0e-2
      relinearize_threshold_bias_acc: 1.0e-1
      relinearize_threshold_bias_gyro: 1.0e-1
      relinearize_threshold_gravity: 1.0e-2
      relinearize_skip: 1
      enable_relinearization: true
      evaluate_nonlinear_error: false
      factorization: QR
      cache_linearized_factors: true
      enable_detailed_results: false
      enable_partial_relinearization_check: true
      initial_position_sigma: 1.0e-6
      initial_rotation_yaw_sigma_deg: 1.0e-6
      initial_rotation_pitch_roll_sigma_deg: 1.0e-6 # 10.0 # if gravity_aligned_initialization is true, then this should be set to 10.0
      initial_velocity_sigma: 5 # This value should not actually matter
      initial_bias_acc_sigma: 0.5
      initial_bias_gyro_sigma: 0.5
      initial_gravity_sigma: 0.2
      additional_update_iterations: 5 # An update does 1 single GN step. Hence 5 updates means a maximum of 5 GN steps.


lidar:
  sensor_frame: mimosa_lidar
  T_B_S: [-0.006253, 0.011775, 0.0028525, 0, 0, 0, 1] # x, y, z, x, y, z, w
  T_B_OdometryLoggerFrame: [0.014, -0.012, -0.106, 0.003, -0.005, -0.002, 1.000] # x, y, z, x, y, z, w
  manager:
    log_level: trace
    enabled: true
    use_to_init: true
    initial_skip: 0 # number of initial pointclouds to drop
    ts_offset: 0
    range_min: 0.5
    range_max: 100
    intensity_min: 0
    intensity_max: 1.0e+10
    create_full_res_pointcloud: true
    full_res_pointcloud_publish_rate_divisor: 2
    use_reflectivity_as_intensity: false
    scale_intensity_by_sq_range: false
    near_range_correction: true # Currently requires minimum range of 2m
  geometric:
    log_level: trace
    enabled: true
    point_skip_divisor: 4 # keep if point.index_in_ring % point_skip_divisor == 0
    ring_skip_divisor: 1  # keep if point.ring % ring_skip_divisor == 0
    map_keyframe_trans_thresh: 2
    map_keyframe_rot_thresh_deg: 30
    lru_horizon: 1000
    neighbor_voxel_mode: 19
    scan_to_map:
      source_voxel_grid_filter_leaf_size: 0.5
      target_ivox_map_leaf_size: 0.5
      num_corres_points: 5
      max_corres_distance: 1
      plane_validity_distance: 0.07
      lidar_point_noise_std_dev: 0.07
      use_huber: true
      huber_threshold: 1.345
      reg_4_dof: false
      project_on_degneneracy: false
      degen_thresh_trans: 0 # 0.01 # m
      degen_thresh_rot: 0 # 0.03 # 0.05 # deg
  photometric:
    log_level: error
    enabled: true
    destagger: true
    visualize: false
    range_min: 0.5 # Needed to avoid division by zero
    range_max: 30
    erosion_buffer: 10
    patch_size: 5
    margin_size: 10
    intensity_scale: 0.25
    intensity_gamma: 1
    remove_lines: true
    filter_brightness: true
    gaussian_blur: true
    gaussian_blur_size: 3
    gradient_threshold: 10
    max_dist_from_mean: 3
    max_dist_from_plane: 0.5
    num_features_detect: 60
    keyframe_num_features_min: 15
    consecutive_frame_num_features_detect: 10
    nma_radius: 11
    occlusion_range_diff_threshold: 0.2
    max_feature_life_time: 100
    high_pass_fir: [-0.00122687, -0.00152587,  0.0009631,   0.00382838,  0.00071422, -0.00765637, -0.00681285,  0.01015542,  0.01944999, -0.00536835, -0.03792929, -0.01565801,  0.05816374,  0.07138264, -0.07402277, -0.30572514,  0.5802669,  -0.30572514, -0.07402277,  0.07138264,  0.05816374, -0.01565801, -0.03792929, -0.00536835,  0.01944999,  0.01015542, -0.00681285, -0.00765637,  0.00071422,  0.00382838,  0.0009631,  -0.00152587, -0.00122687]
    low_pass_fir: [-0.0013038,  -0.00117813, -0.00102349, -0.00051396,  0.000759,    0.00322145, 0.00724004,  0.01304552,  0.02066957,  0.02990645,  0.04030759,  0.0512121, 0.06181081,  0.07123596,  0.07866427,  0.08341891,  0.08505541,  0.08341891, 0.07866427,  0.07123596,  0.06181081,  0.0512121,   0.04030759,  0.02990645, 0.02066957,  0.01304552,  0.00724004,  0.00322145,  0.000759,   -0.00051396, -0.00102349, -0.00117813, -0.0013038, ]
    brightness_window_size: [41, 7]
    use_robust_cost_function: false
    robust_cost_function: huber
    robust_cost_function_parameter: 1.345
    error_scale: 1
    sigma: 0.25
    max_error: 0.3
